name: "CI"

on: ["push", "pull_request"]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        node_version:
          - 16
          - 18

    name: "Node ${{ matrix.node_version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Set up Node ${{ matrix.node_version }}"
        uses: "actions/setup-node@v3"
        with:
          node-version: ${{ matrix.node_version }}
          cache: "yarn"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Test building package"
        run: "yarn run build"

      - name: "Run linting"
        run: "yarn run lint"

      - name: "Run tests"
        run: "yarn run test --full-trace"

  docs:
    strategy:
      fail-fast: false

    name: "Doc Link Checker"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Run Doc Link Checker"
        uses: "docker://ghcr.io/djmattyg007/doc-link-checker:1.0.4@sha256:ef7c7e7f718526e7d2671cc75ad55f1d8d5207e90d1ea8d594134045e1476448"
        with:
          args: "lint --exclude-extend tests/fixtures/**"
        env:
          DOC_LINK_CHECKER_MDTYPE: "gfm"
