name: "CI"

on: ["push", "pull_request"]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        node_version:
          - 16
          - 18

    name: "Node ${{ matrix.node_version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Set up Node ${{ matrix.node_version }}"
        uses: "actions/setup-node@v3"
        with:
          node-version: ${{ matrix.node_version }}
          cache: "yarn"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Test building package"
        run: "yarn run build"

      - name: "Run linting"
        run: "yarn run lint"

      - name: "Run tests"
        run: "yarn run test"
