name: "Release"

on:
  release:
    types: ["published"]

jobs:
  release:
    runs-on: "ubuntu-24.04"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Set up Node 16"
        uses: "actions/setup-node@v4"
        with:
          node-version: 16
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Build package"
        run: "yarn run build"

      - name: "Publish package"
        run: "yarn npm publish --access public"
        env:
          YARN_NPM_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
